# Generated by Django 3.1.3 on 2020-11-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=2, max_length=75),
            preserve_default=False,
        ),
    ]
