# Generated by Django 3.1.3 on 2020-11-11 23:17

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
