# Generated by Django 3.1.3 on 2020-11-11 23:51

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
